services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    user: postgres
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  molprobity:
    image: molprobity
    build:
      context: ./molprobity
    restart: always
    #ports:
    #  - 3015:3001
    volumes:
      - user_data:/user_data
    scale: 4

  tools:
    image: tools
    build:
      context: ./tools
    environment:
      NODE_ENV: production
    # ports:
    #   - 3003:3003
    volumes:
      - user_data:/usr/src/app/user_data
    scale: 1

  restapi:
    image: restapi
    build:
      context: ./restapi
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - ./restapi/.env
    ports:
      - 3001:3001
    volumes:
      - user_data:/usr/src/app/public/jobs
    depends_on:
      - db
      - redis
    scale: 1

  frontend:
    image: frontend
    build:
      context: ./frontend
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - restapi

  sim:
    image: sim
    build:
      context: ./sim
    restart: always
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SIM_WORKER_CONCURRENCY: 1
    ports:
      - 3004:3001
    volumes:
      - user_data:/usr/src/app/public/jobs
    depends_on:
      - redis
    scale: 1

volumes:
  db_data:
    driver: local
  user_data:
    driver: local
  redis_data:
    driver: local
