services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    user: postgres
    # expose:
    #   - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    # secrets:
    #   - db-password

  # adminer:
  #   image: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080

  molprobity:
    image: dawidgrajek1/molprobity:latest
    restart: always
    # ports:
    #   - 3004:3004
    volumes:
      - user_data:/user_data
    scale: 6

  tools:
    image: tools
    build:
      context: ./tools
    environment:
      NODE_ENV: production
    # ports:
    #   - 3003:3003
    volumes:
      - user_data:/usr/src/app/user_data
    scale: 1

  restapi:
    image: restapi
    build:
      context: ./restapi
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - ./restapi/.env
    ports:
      - 3001:3001
    volumes:
      - user_data:/usr/src/app/public/jobs
    depends_on:
      - db
    scale: 1
    
  frontend:
    image: frontend
    build:
      context: ./frontend
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - restapi


volumes:
  db_data:
    driver: local
  user_data:
    driver: local

# secrets:
#   db-password:
#     file: db/password.txt
